fj-25-financas-web/src/br/com/caelum/financas/mb/CacheBean.java
package br.com.caelum.financas.mb;

import br.com.caelum.financas.modelo.Conta;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;


@Named
@RequestScoped
public class CacheBean {
	
	private Integer id;
	private Conta conta;
	
	@Inject
	private EntityManager manager;
	
	public void pesquisar() {
		  //System.out.println("Testando cache de primeiro nivel");
			System.out.println("Testando cache de segundo nivel");
			this.conta = this.manager.find(Conta.class, id);
			this.conta = this.manager.find(Conta.class, id);
	}

	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Conta getConta() {
		return conta;
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/CacheInvalidaBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.Cache;

import br.com.caelum.financas.modelo.Conta;

@Named
@RequestScoped
public class CacheInvalidaBean {
	
	private Integer id;
	private Conta conta;
	
	@Inject
	private Cache cache;
	
	public void invalidar() {
		System.out.println("Invalidando o cache programaticamente");
		cache.evict(Conta.class, this.id);
	}

	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	
	public Conta getConta() {
		return conta;
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/CicloDeVidaBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.service.Agendador;

@Named
@RequestScoped
public class CicloDeVidaBean {
	
	@Inject
	private Agendador agendador;
	
	public void executeAgendador() {
		agendador.executa();
	
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/ContasBean.java
package br.com.caelum.financas.mb;

import java.io.Serializable;
import java.util.List;

import br.com.caelum.financas.dao.ContaDao;
import br.com.caelum.financas.modelo.Conta;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@ViewScoped
public class ContasBean implements Serializable {
    
    private static final long serialVersionUID = 1L;

	private Conta conta = new Conta();
	private List<Conta> contas;
	@Inject
	private ContaDao contaDao;
		
	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public void grava() {
		if (conta.getId() == null){
			System.out.println("Gravando a conta");
			contaDao.adiciona(conta);
		}else{
			System.out.println("Alterando a conta");
			contaDao.altera(conta);
		}
		this.contas = contaDao.lista();
		limpaFormularioDoJSF();
	}

	public List<Conta> getContas() {
		if (this.contas == null){
			this.contas = contaDao.lista();
		}

		return contas;
	}

	public void remove() {
		contaDao.remove(this.conta);
		System.out.println("Removendo a conta");
		this.contas = contaDao.lista();
		limpaFormularioDoJSF();
	}

	/**
	 * Esse metodo apenas limpa o formulario da forma com que o JSF espera.
	 * Invoque-o no momento em que precisar do formulario vazio.
	 */
	private void limpaFormularioDoJSF() {
		this.conta = new Conta();
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/CriteriaBean.java
package br.com.caelum.financas.mb;

import java.math.BigDecimal;
import java.util.List;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Movimentacao;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class CriteriaBean {
	
	private List<Movimentacao> movimentacoes;
	private BigDecimal soma;
	
	private String titular;
	
	@Inject
	private MovimentacaoDao movimentacaoDao;
	
	public void listarTodasAsMovimentacoes() {
		this.movimentacoes = movimentacaoDao.listaTodasComCriteria();
	}

	public void somaMovimentacoesDoTitular() {
		this.movimentacoes = movimentacaoDao.listaTodasComCriteria();
		this.soma = movimentacaoDao.somaMovimentacoesDoTiTtular(this.titular);
	}
	
	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}
	
	public BigDecimal getSoma() {
		return soma;
	}
	
	public String getTitular() {
		return titular;
	}
	
	public void setTitular(String titular) {
		this.titular = titular;
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/EstatisticasBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.hibernate.Session;
import org.hibernate.stat.Statistics;

@Named
@ApplicationScoped
public class EstatisticasBean {
	
	@Inject
	private EntityManager manager;

	private Statistics estatisticas;
	
	public void gera() {
		System.out.println("Gerando estátisticas");
		Session session = manager.unwrap(Session.class);
		this.estatisticas = session.getSessionFactory().getStatistics();
	}

	public Statistics getEstatisticas() {
		return estatisticas;
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/MesesComMovimentacaoBean.java
package br.com.caelum.financas.mb;


import java.util.List;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.TipoMovimentacao;
import br.com.caelum.financas.modelo.ValorPorMesEAno;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class MesesComMovimentacaoBean {

	private Conta conta = new Conta();
	private List<ValorPorMesEAno> valoresPorMesEAno;

	private TipoMovimentacao tipoMovimentacao;
	
	@Inject
	private MovimentacaoDao movimentacaoDao;
	
	public void lista() {
		System.out.println("Listando as contas pelos valores movimentados no mes");
		this.valoresPorMesEAno = movimentacaoDao.listaMesesComMovimentacoes(conta, tipoMovimentacao);
	}
	
	public List<ValorPorMesEAno> getValoresPorMesEAno() {
		return valoresPorMesEAno;
	}

	public TipoMovimentacao getTipoMovimentacao() {
		return tipoMovimentacao;
	}

	public void setTipoMovimentacao(TipoMovimentacao tipoMovimentacao) {
		this.tipoMovimentacao = tipoMovimentacao;
	}

	public Conta getConta() {
		return conta;
	}

}

fj-25-financas-web/src/br/com/caelum/financas/mb/MovimentacoesBean.java
package br.com.caelum.financas.mb;

import java.io.Serializable;
import java.util.Calendar;
import java.util.List;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import br.com.caelum.financas.dao.CategoriaDao;
import br.com.caelum.financas.dao.ContaDao;
import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Categoria;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.Movimentacao;
import br.com.caelum.financas.modelo.TipoMovimentacao;

@Named
@ViewScoped
public class MovimentacoesBean implements Serializable {

	private static final long serialVersionUID = 1L;
	
	private List<Categoria> categorias;
	private List<Movimentacao> movimentacoes;
	private Movimentacao movimentacao = new Movimentacao();
	private Integer contaId;
	private Integer categoriaId;
	
	@Inject
	private MovimentacaoDao movimentacaoDao;
	@Inject
	private ContaDao contaDao;
	@Inject
	private CategoriaDao categoriaDao;
	
	public void grava() {
		System.out.println("Fazendo a gravacao da movimentacao");
		Conta contaRelacionada = contaDao.busca(contaId);
		movimentacao.setConta(contaRelacionada);
		
		movimentacaoDao.adiciona(movimentacao);
		this.movimentacoes = movimentacaoDao.lista();
		limpaFormularioDoJSF();
	}
	

	public void remove() {
		System.out.println("Removendo a movimentacao");
		movimentacaoDao.remove(this.movimentacao);
		
		limpaFormularioDoJSF();
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}
	
	public Movimentacao getMovimentacao() {
		if(movimentacao.getData()==null) {
			movimentacao.setData(Calendar.getInstance());
			this.movimentacoes = movimentacaoDao.lista();
		}
		return movimentacao;
	}

	public void setMovimentacao(Movimentacao movimentacao) {
		this.movimentacao = movimentacao;
	}

	public Integer getContaId() {
		return contaId;
	}

	public void setContaId(Integer contaId) {
		this.contaId = contaId;
	}
	

	public Integer getCategoriaId() {
		return categoriaId;
	}

	public void setCategoriaId(Integer categoriaId) {
		this.categoriaId = categoriaId;
	}

	/**
	 * Esse metodo apenas limpa o formulario da forma com que o JSF espera.
	 * Invoque-o no momento manager que precisar do formulario vazio.
	 */
	private void limpaFormularioDoJSF() {
		this.movimentacao = new Movimentacao();
	}

	public TipoMovimentacao[] getTiposDeMovimentacao() {
		return TipoMovimentacao.values();
	}
	
	public void adicionaCategoria(){
		if (this.categoriaId != null & this.categoriaId > 0){
			Categoria categoria = categoriaDao.procura(this.categoriaId);
			this.movimentacao.getCategorias().add(categoria);
		}
	}
	
	public List<Categoria> getCategorias(){
		if (this.categorias == null){
			this.categorias = categoriaDao.lista();
		}
		return this.categorias;
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/MovimentacoesDaContaBean.java
package br.com.caelum.financas.mb;

import java.util.List;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.Movimentacao;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class MovimentacoesDaContaBean {

	private List<Movimentacao> movimentacoes;
	private Conta conta = new Conta();
	
	@Inject
	MovimentacaoDao movimentacaoDao;
	
	public void lista() {
		movimentacoes = movimentacaoDao.listaTodasMovimentacoes(conta);
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/MovimentacoesPorTitularBean.java
package br.com.caelum.financas.mb;

import java.util.List;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Movimentacao;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class MovimentacoesPorTitularBean {

	private List<Movimentacao> movimentacoes;
	private String titular;
	
	@Inject
	private MovimentacaoDao movimentacaoDao;

	public void lista() {
		System.out.println("Buscando as movimentacoes pelo titular da conta " + this.titular);
		this.movimentacoes = movimentacaoDao.buscaTodasMovimentacoesDaConta(titular);
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

	public String getTitular() {
		return titular;
	}

	public void setTitular(String titular) {
		this.titular = titular;
	}

}

fj-25-financas-web/src/br/com/caelum/financas/mb/MovimentacoesPorValorETipoBean.java
package br.com.caelum.financas.mb;

import java.math.BigDecimal;
import java.util.List;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Movimentacao;
import br.com.caelum.financas.modelo.TipoMovimentacao;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class MovimentacoesPorValorETipoBean {
	
	private List<Movimentacao> movimentacoes;
	private BigDecimal valor;
	private TipoMovimentacao tipoMovimentacao;

	@Inject
	MovimentacaoDao movimentacaoDao;

	public void lista() {
		movimentacoes = movimentacaoDao.listaPorValorETipo(valor, tipoMovimentacao);
	}

	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public TipoMovimentacao getTipoMovimentacao() {
		return tipoMovimentacao;
	}

	public void setTipoMovimentacao(TipoMovimentacao tipoMovimentacao) {
		this.tipoMovimentacao = tipoMovimentacao;
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

}

fj-25-financas-web/src/br/com/caelum/financas/mb/OperacaoEmLoteBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class OperacaoEmLoteBean {
	
	private String antigoNomeBanco;
	private String novoNomeBanco;
	private int contasAlteradas;
	
	public void atualizar() {

		
		
		System.out.println("Quantidade de contas alteradas: " + contasAlteradas);
		this.limpaFormularioDoJSF();
	}

	public String getAntigoNomeBanco() {
		return antigoNomeBanco;
	}

	public void setAntigoNomeBanco(String antigoNomeBanco) {
		this.antigoNomeBanco = antigoNomeBanco;
	}

	public String getNovoNomeBanco() {
		return novoNomeBanco;
	}

	public void setNovoNomeBanco(String novoNomeBanco) {
		this.novoNomeBanco = novoNomeBanco;
	}

	public int getContasAlteradas() {
		return contasAlteradas;
	}

	private void limpaFormularioDoJSF() {
		this.antigoNomeBanco = "";
		this.novoNomeBanco = "";
	}	
	
}

fj-25-financas-web/src/br/com/caelum/financas/mb/PesquisaMovimentacoesBean.java
package br.com.caelum.financas.mb;

import java.util.List;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.Movimentacao;
import br.com.caelum.financas.modelo.TipoMovimentacao;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class PesquisaMovimentacoesBean {

	private Conta conta = new Conta();
	private Integer mes;
	private TipoMovimentacao tipoMovimentacao;
	private List<Movimentacao> movimentacoes;

	@Inject
	private MovimentacaoDao movimentacaoDao;
	
	public void pesquisa() {
		System.out.println("Pesquisando pelos filtros solicitados");
		this.movimentacoes = movimentacaoDao.pesquisa(conta, tipoMovimentacao, mes);

	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

	public Conta getConta() {
		if(conta.getId()!=null && conta.getId()==0) {
			conta.setId(null);
		}
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public Integer getMes() {	
		if(mes!=null && mes==0) {
			mes=null;
		}
		return mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	public TipoMovimentacao getTipoMovimentacao() {
		return tipoMovimentacao;
	}

	public void setTipoMovimentacao(TipoMovimentacao tipoMovimentacao) {
		this.tipoMovimentacao = tipoMovimentacao;
	}

}

fj-25-financas-web/src/br/com/caelum/financas/mb/QtdeMovimentacoesDaContaBean.java
package br.com.caelum.financas.mb;

import br.com.caelum.financas.dao.ContaDao;
import br.com.caelum.financas.modelo.Conta;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;


@Named
@RequestScoped
public class QtdeMovimentacoesDaContaBean {
	
	private Conta conta = new Conta();
	private int quantidade;
	
	@Inject
	private ContaDao contaDao;
	
	public void lista() {
		this.conta = contaDao.busca(conta.getId());
		this.quantidade = conta.getMovimentacoes().size();
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public int getQuantidade() {
		return quantidade;
	}

	public void setQuantidade(int quantidade) {
		this.quantidade = quantidade;
	}
}

fj-25-financas-web/src/br/com/caelum/financas/mb/SearchIndexacaoBean.java
package br.com.caelum.financas.mb;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class SearchIndexacaoBean {


	public void indexar() throws InterruptedException {

	}
	
}

fj-25-financas-web/src/br/com/caelum/financas/mb/SearchPesquisaTextualBean.java
package br.com.caelum.financas.mb;

import java.util.List;
import br.com.caelum.financas.modelo.Movimentacao;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class SearchPesquisaTextualBean {

	private String descricao;
	private List<Movimentacao> movimentacoes;
	
	
	public void pesquisar() {

	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public List<Movimentacao> getMovimentacoes() {
		return movimentacoes;
	}

}

fj-25-financas-web/src/br/com/caelum/financas/mb/TotalMovimentadoBean.java
package br.com.caelum.financas.mb;

import java.math.BigDecimal;

import br.com.caelum.financas.dao.MovimentacaoDao;
import br.com.caelum.financas.modelo.Conta;
import br.com.caelum.financas.modelo.TipoMovimentacao;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

@Named
@RequestScoped
public class TotalMovimentadoBean {
	
	private BigDecimal total;
	private Conta conta = new Conta();
	private TipoMovimentacao tipoMovimentacao;
	
	@Inject
	MovimentacaoDao movimentacaoDao;

	public void calcula() {
		this.total = this.movimentacaoDao.calculaTotalMovimentado(conta, tipoMovimentacao);
		System.out.println("Total movimentado pela conta");

	}

	public BigDecimal getTotal() {
		return total;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public TipoMovimentacao getTipoMovimentacao() {
		return tipoMovimentacao;
	}

	public void setTipoMovimentacao(TipoMovimentacao tipoMovimentacao) {
		this.tipoMovimentacao = tipoMovimentacao;
	}

}

fj-25-financas-web/WebContent/agendamento.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			  <html xmlns="http://www.w3.org/1999/xhtml"
					xmlns:ui="http://java.sun.com/jsf/facelets"
					xmlns:f="http://java.sun.com/jsf/core"
					xmlns:h="http://java.sun.com/jsf/html">

    <ui:composition template="/_template.xhtml">
    
    	<ui:define name="cabecalho">
		   <h:outputText value="EJB 3: Timer Service" />
    	</ui:define>
		   
   		<ui:define name="corpo">

		<h:form>
			<h:panelGrid columns="3">
			<h:outputText value="Expressão Minutos:" />
			<h:inputText value="#{agendadorFormBean.expressaoMinutos}" />	  
			<h:outputText value="Exemplos: */1 - cada minuto, 10 - as 10 minutos" />
			
			<h:outputText value="Expressão Segundos:" />
			<h:inputText value="#{agendadorFormBean.expressaoSegundos}" />
			<h:outputText value="Exemplos: 10-20 - entre 10 e 20, 30/5 - segundos 30,35,40,45,50,55" />

			 
			<h:commandButton value="Submeter agendamento" actionListener="#{agendadorFormBean.agendar}"/>
			</h:panelGrid>
		</h:form>
	    
	       <p><h:outputText value="Após ter submetido o formulário verfique o console." /></p>
		</ui:define>
	</ui:composition>
</html>

fj-25-financas-web/WebContent/mesesComMovimentacao.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			  <html xmlns="http://www.w3.org/1999/xhtml"
					xmlns:ui="http://java.sun.com/jsf/facelets"
					xmlns:f="http://java.sun.com/jsf/core"
					xmlns:h="http://java.sun.com/jsf/html">

    <ui:composition template="/_template.xhtml">
   		<ui:define name="cabecalho">
		   <h:outputText value="Movimentações por mês" />
    	</ui:define>
		   
   		<ui:define name="corpo">
			 <h:form>
			  	<h:panelGrid columns="2">
			  		<h:outputText value="Conta"/>
			      	<h:selectOneMenu value="#{mesesComMovimentacaoBean.conta.id}">
			      		<f:selectItem itemLabel="Escolha a conta" itemValue="" noSelectionOption="true"/>
			      		<f:selectItems value="#{contasBean.contas}" var="conta" itemLabel="#{conta.titular} - #{conta.banco}" itemValue="#{conta.id}" />
			      	</h:selectOneMenu>
			      	
			      	<h:outputText value="Tipo" />
				   	<h:selectOneMenu value="#{mesesComMovimentacaoBean.tipoMovimentacao}">
				   		<f:selectItem itemLabel="Escolha o tipo" itemValue="" noSelectionOption="true"/>
				   		<f:selectItems value="#{movimentacoesBean.tiposDeMovimentacao}" />
				   	</h:selectOneMenu>
			     	
			  		<h:commandButton value="Pesquisar" action="#{mesesComMovimentacaoBean.lista}"/>
				</h:panelGrid>
			</h:form>
    
	        <h2><h:outputText value="Todas as Movimentações" /></h2>
	        <hr />
	        <h:dataTable value="#{mesesComMovimentacaoBean.valoresPorMesEAno}" var="valorPorMesEAno">
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Mês" />
	        		</f:facet>
	        		#{valorPorMesEAno.mes}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Ano" />
	        		</f:facet>
	        		#{valorPorMesEAno.ano}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Valor" />
	        		</f:facet>
	        		#{valorPorMesEAno.valor}
	        	</h:column>
	        </h:dataTable>
    		</ui:define>
	</ui:composition>
</html>

fj-25-financas-web/WebContent/pesquisaMovimentacoes.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
			  <html xmlns="http://www.w3.org/1999/xhtml"
					xmlns:ui="http://java.sun.com/jsf/facelets"
					xmlns:f="http://java.sun.com/jsf/core"
					xmlns:h="http://java.sun.com/jsf/html">

    <ui:composition template="/_template.xhtml">
    	<ui:define name="cabecalho">
		   <h:outputText value="Movimentações com filtro dinámico com Criteria" />
    	</ui:define>
		   
   		<ui:define name="corpo">
		   <h:form>
		    	<h:panelGrid columns="2">
		    		<h:outputText value="Conta"/>
		        	<h:selectOneMenu value="#{pesquisaMovimentacoesBean.conta.id}">
		        		<f:selectItem itemLabel="Escolha a conta" itemValue="" noSelectionOption="true"/>
		        		<f:selectItems value="#{contasBean.contas}" var="conta" itemLabel="#{conta.titular} - #{conta.banco}" itemValue="#{conta.id}" />
		        	</h:selectOneMenu>
		        	
		        	<h:outputText value="Tipo" />
			    	<h:selectOneMenu value="#{pesquisaMovimentacoesBean.tipoMovimentacao}">
			    		<f:selectItem itemLabel="Escolha o tipo" itemValue="" noSelectionOption="true"/>
			    		<f:selectItems value="#{movimentacoesBean.tiposDeMovimentacao}" />
			    	</h:selectOneMenu>
			    	
		        	<h:outputText value="Mês" />
					<h:inputText id="mes" value="#{pesquisaMovimentacoesBean.mes}">
						<f:validateLongRange minimum="1" maximum="12"/>
					</h:inputText>							    		        
		    		<h:commandButton value="Pesquisar" action="#{pesquisaMovimentacoesBean.pesquisa}"/>
				</h:panelGrid>
		   </h:form>
    
	        <h:dataTable value="#{pesquisaMovimentacoesBean.movimentacoes}" var="movimentacao" rendered="#{pesquisaMovimentacoesBean.movimentacoes != null}">
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="ID" />
	        		</f:facet>
	        		#{movimentacao.id}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Conta" />
	        		</f:facet>
	        		#{movimentacao.conta.titular} - #{movimentacao.conta.banco}
	        	</h:column>
	        	<h:column>
					<f:facet name="header">
						<h:outputText value="Valor" />
					</f:facet>
					<h:outputText value="#{movimentacao.valor}" >
						<f:convertNumber pattern="R$ #0.00"/>
					</h:outputText>
				</h:column>
				<h:column>
					<f:facet name="header">
						<h:outputText value="Data" />
					</f:facet>
					<h:outputText value="#{movimentacao.data.time}" >
						<f:convertDateTime pattern="dd/MM/yyyy" />
					</h:outputText>
				</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Descrição" />
	        		</f:facet>
	        		#{movimentacao.descricao}
	        	</h:column>
	        	<h:column>
	        		<f:facet name="header">
	        			<h:outputText value="Tipo" />
	        		</f:facet>
	        		#{movimentacao.tipoMovimentacao}
	        	</h:column>
	        </h:dataTable>
		</ui:define>
	</ui:composition>
</html>